### ISSUE TITLE
Teared Link

### ISSUE THREAD

**Issue by lwihler** [orbiting/pdf#133] opened 2018-11-27 14:17 UTC
https://cdn.republik.space/pdf/2018/11/27/meine-gluecksdrachen.pdf

<img width="996" alt="bildschirmfoto 2018-11-27 um 15 16 47" src="https://user-images.githubusercontent.com/38752973/49087566-96bf5c00-f257-11e8-99b1-69d172ed70ff.png">

S.8 ist leer

**Comment by tpreusse** [comment] 2018-12-07 15:55
duplicate of https://github.com/orbiting/pdf/issues/129

**Closed by tpreusse** 2018-12-07 15:55 UTC
